### ISSUE TITLE
summary command

### ISSUE THREAD

**Issue by tenvinc** [CS2113-AY1819S1-T09-4/main#30]

**Comment by tenvinc** [comment]
- [ ] Implement a summary map to keep track of summary
- [ ] Implement a storage for the summary
- [ ] Implement Command Result version of summary
- [ ] Implement UI for displaying summary table
- [ ] Implement tests for summary

**Comment by tenvinc** [comment]
Aborted
