### ISSUE TITLE
Archiving after a long period

### ISSUE THREAD

**Issue by tenvinc** [CS2113-AY1819S1-T09-4/main#32]
- [x] Write the Export Excel Command

- [x] Write the Export Excel Command Parser

- [x] Write the Export Excel Command Test

- [x] Write the Export Excel Command Parser test
