### ISSUE TITLE
Advanced Summary

### ISSUE THREAD

**Issue by tenvinc** [CS2113-AY1819S1-T09-4/main#78]
- [x] Summary by date
- [x] Tests for that
- [x] Summary by month
- [x] Tests for that
- [x] Summary for categories
- [x] Tests for that
- [x] Link up with the computer time stamp
- [x] UI to display summary for this month by default

**Comment by tenvinc** [comment]
Parsertests:
- [ ] SummaryByDateParser
- [ ] SummaryByMonthParser
- [ ] SummaryParser
- [ ] MonthTest

**Comment by tenvinc** [comment]
Changing parserUtil tests
- [ ] modify date related tests
- [ ] modify money related tests
- [ ] add month related tests

**Comment by tenvinc** [comment]
SummaryList tests
- [ ] SummaryByMonthList
- [ ] SummaryByDateList
