### ISSUE TITLE
Set the path to save the Excel file 

### ISSUE THREAD

**Issue by nguyenngoclinhchi** [CS2113-AY1819S1-T09-4/main#85]
- [ ] Modify in the model to add Directory Path

- [ ] Modify in the Storage to store the path 

- [ ] Fix all the test relating to the project

- [ ] (Optional) Modify in UI to create pop-up window to choose the directory

- [ ] Create the Set-path command

- [ ] Create the Set-path Command parser

- [ ] Create Set-path command test 

- [ ] Create set-path command parser test
